import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        body: "var(--font-body)",
        display: "var(--font-display)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        'xs': ['var(--text-xs)', { lineHeight: 'var(--text-xs--line-height)' }],
        'sm': ['var(--text-sm)', { lineHeight: 'var(--text-sm--line-height)' }],
        'md': ['var(--text-md)', { lineHeight: 'var(--text-md--line-height)' }],
        'lg': ['var(--text-lg)', { lineHeight: 'var(--text-lg--line-height)' }],
        'xl': ['var(--text-xl)', { lineHeight: 'var(--text-xl--line-height)' }],
        'display-xs': ['var(--text-display-xs)', { lineHeight: 'var(--text-display-xs--line-height)' }],
        'display-sm': ['var(--text-display-sm)', { lineHeight: 'var(--text-display-sm--line-height)' }],
        'display-md': ['var(--text-display-md)', { lineHeight: 'var(--text-display-md--line-height)', letterSpacing: 'var(--text-display-md--letter-spacing)' }],
        'display-lg': ['var(--text-display-lg)', { lineHeight: 'var(--text-display-lg--line-height)', letterSpacing: 'var(--text-display-lg--letter-spacing)' }],
        'display-xl': ['var(--text-display-xl)', { lineHeight: 'var(--text-display-xl--line-height)', letterSpacing: 'var(--text-display-xl--letter-spacing)' }],
        'display-2xl': ['var(--text-display-2xl)', { lineHeight: 'var(--text-display-2xl--line-height)', letterSpacing: 'var(--text-display-2xl--letter-spacing)' }],
      },
      colors: {
        // shadcn/ui compatibility
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Design system colors
        brand: {
          25: "var(--color-brand-25)",
          50: "var(--color-brand-50)",
          100: "var(--color-brand-100)",
          200: "var(--color-brand-200)",
          300: "var(--color-brand-300)",
          400: "var(--color-brand-400)",
          500: "var(--color-brand-500)",
          600: "var(--color-brand-600)",
          700: "var(--color-brand-700)",
          800: "var(--color-brand-800)",
          900: "var(--color-brand-900)",
          950: "var(--color-brand-950)",
        },
        error: {
          25: "var(--color-error-25)",
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
        },
        warning: {
          25: "var(--color-warning-25)",
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
        },
        success: {
          25: "var(--color-success-25)",
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
        },
        purple: {
          25: "var(--color-purple-25)",
          50: "var(--color-purple-50)",
          100: "var(--color-purple-100)",
          200: "var(--color-purple-200)",
          300: "var(--color-purple-300)",
          400: "var(--color-purple-400)",
          500: "var(--color-purple-500)",
          600: "var(--color-purple-600)",
          700: "var(--color-purple-700)",
          800: "var(--color-purple-800)",
          900: "var(--color-purple-900)",
          950: "var(--color-purple-950)",
        },
        green: {
          25: "var(--color-green-25)",
          50: "var(--color-green-50)",
          100: "var(--color-green-100)",
          200: "var(--color-green-200)",
          300: "var(--color-green-300)",
          400: "var(--color-green-400)",
          500: "var(--color-green-500)",
          600: "var(--color-green-600)",
          700: "var(--color-green-700)",
          800: "var(--color-green-800)",
          900: "var(--color-green-900)",
          950: "var(--color-green-950)",
        },
        orange: {
          25: "var(--color-orange-25)",
          50: "var(--color-orange-50)",
          100: "var(--color-orange-100)",
          200: "var(--color-orange-200)",
          300: "var(--color-orange-300)",
          400: "var(--color-orange-400)",
          500: "var(--color-orange-500)",
          600: "var(--color-orange-600)",
          700: "var(--color-orange-700)",
          800: "var(--color-orange-800)",
          900: "var(--color-orange-900)",
          950: "var(--color-orange-950)",
        },
        pink: {
          25: "var(--color-pink-25)",
          50: "var(--color-pink-50)",
          100: "var(--color-pink-100)",
          200: "var(--color-pink-200)",
          300: "var(--color-pink-300)",
          400: "var(--color-pink-400)",
          500: "var(--color-pink-500)",
          600: "var(--color-pink-600)",
          700: "var(--color-pink-700)",
          800: "var(--color-pink-800)",
          900: "var(--color-pink-900)",
          950: "var(--color-pink-950)",
        },
        yellow: {
          25: "var(--color-yellow-25)",
          50: "var(--color-yellow-50)",
          100: "var(--color-yellow-100)",
          200: "var(--color-yellow-200)",
          300: "var(--color-yellow-300)",
          400: "var(--color-yellow-400)",
          500: "var(--color-yellow-500)",
          600: "var(--color-yellow-600)",
          700: "var(--color-yellow-700)",
          800: "var(--color-yellow-800)",
          900: "var(--color-yellow-900)",
          950: "var(--color-yellow-950)",
        },
        // Semantic colors
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-quaternary': 'var(--color-text-quaternary)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'text-brand-primary': 'var(--color-text-brand-primary)',
        'text-brand-secondary': 'var(--color-text-brand-secondary)',
        'text-error-primary': 'var(--color-text-error-primary)',
        'text-warning-primary': 'var(--color-text-warning-primary)',
        'text-success-primary': 'var(--color-text-success-primary)',
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'bg-quaternary': 'var(--color-bg-quaternary)',
        'bg-disabled': 'var(--color-bg-disabled)',
        'bg-brand-primary': 'var(--color-bg-brand-primary)',
        'bg-brand-secondary': 'var(--color-bg-brand-secondary)',
        'bg-brand-solid': 'var(--color-bg-brand-solid)',
        'bg-error-primary': 'var(--color-bg-error-primary)',
        'bg-warning-primary': 'var(--color-bg-warning-primary)',
        'bg-success-primary': 'var(--color-bg-success-primary)',
        'border-primary': 'var(--color-border-primary)',
        'border-secondary': 'var(--color-border-secondary)',
        'border-tertiary': 'var(--color-border-tertiary)',
        'border-brand': 'var(--color-border-brand)',
        'border-error': 'var(--color-border-error)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'DEFAULT': 'var(--radius-DEFAULT)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        '3xl': 'var(--shadow-3xl)',
        'skeumorphic': 'var(--shadow-skeumorphic)',
        'xs-skeumorphic': 'var(--shadow-xs-skeumorphic)',
        'modern-mockup-inner-lg': 'var(--shadow-modern-mockup-inner-lg)',
        'modern-mockup-inner-md': 'var(--shadow-modern-mockup-inner-md)',
        'modern-mockup-inner-sm': 'var(--shadow-modern-mockup-inner-sm)',
        'modern-mockup-outer-lg': 'var(--shadow-modern-mockup-outer-lg)',
        'modern-mockup-outer-md': 'var(--shadow-modern-mockup-outer-md)',
        'iphone-mockup': 'var(--drop-shadow-iphone-mockup)',
      },
      maxWidth: {
        'container': 'var(--max-width-container)',
      },
      screens: {
        'xxs': 'var(--breakpoint-xxs)',
        'xs': 'var(--breakpoint-xs)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "caret-blink": {
          "0%, 50%": { opacity: "1" },
          "51%, 100%": { opacity: "0" },
        },
        "background-gradient": {
          "0%, 100%": {
            transform: "translate(0, 0) scale(1)",
            animationDelay: "var(--background-gradient-delay, 0s)",
          },
          "25%": {
            transform: "translate(40px, -30px) scale(1.15)",
          },
          "50%": {
            transform: "translate(-25px, 35px) scale(0.85)",
          },
          "75%": {
            transform: "translate(30px, 20px) scale(1.2)",
          },
        },
        "float": {
          "0%, 100%": {
            transform: "translateY(0px) translateX(0px) scale(1)",
          },
          "25%": {
            transform: "translateY(-25px) translateX(15px) scale(1.1)",
          },
          "50%": {
            transform: "translateY(20px) translateX(-20px) scale(0.9)",
          },
          "75%": {
            transform: "translateY(-15px) translateX(10px) scale(1.05)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "marquee": "marquee var(--duration, 30s) linear infinite",
        "caret-blink": "var(--animate-caret-blink)",
        "background-gradient": "background-gradient var(--background-gradient-speed, 15s) cubic-bezier(0.445, 0.05, 0.55, 0.95) infinite",
        "float": "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}

export default config
